### PR TITLE
Design improvements to the launcher popup

### PR DESCRIPTION
**Pull request by iBeliever**
Center the launcher, add an extra row + column, use a square launcher item with only one row of text, and make the launchers use a light gray highlight and ripple.

hawaii_010

### CODE REVIEW

**Comment by plfiorini** [comment]
The look with the light theme is very nice!
Though I'm not sure on centering it, consider that the user will click the button and then she will move the pointer to the center.

**Comment by iBeliever** [comment]
@plfiorini Yeah, that is a potential concern, though since windows will start at different places on the screen, you may have to move your mouse past the center anyway to get to the app you just launched.

With the extra row and column, it's so big that it doesn't really look good not centered, and the reason I added the extra row and column was to save on pages. It seems more efficient to show more applications and fewer pages rather than to save on mouse travel to the launcher.

**Comment by plfiorini** [comment]
I agree it's too big to be on the corner, probably I need to get used to.
Anyway if the popup is operated with the keyboard, say pressing Meta+Space it becomes instant.

I added a commit to set it modal, try it and tell me if you like it.

**Comment by plfiorini** [comment]
@iBeliever If you like it modal merge otherwise delete the commit and merge.

**Comment by iBeliever** [comment]
@plfiorini I like the change, merging.

**Pull request merged**
